const verdades = [
  "¿Qué parte de mi cuerpo te gusta más?",
  "¿Cuál fue tu sueño más caliente conmigo?",
  "¿Te gustaría hacer el amor en un lugar público?",
  "¿Has pensado en otra persona estando conmigo?",
  "¿Cuál es tu fantasía más secreta?",
  "¿Te gustaría probar algo nuevo en la cama?",
  "¿Cuándo fue la última vez que mentiste y por qué?",
  "¿Cuál es tu mayor inseguridad?",
  "¿Te gustaría grabarnos en la intimidad?",
  "¿Has stalkeado a tu ex recientemente?",
  "¿Alguna vez te han pillado en el acto?",
  "¿Cuál ha sido tu experiencia sexual más rara?",
  "¿Has fingido un orgasmo?",
  "¿Con qué frecuencia piensas en sexo?",
  "¿Cuál ha sido tu peor cita?",
  "¿Te gustaría hacer un trío?",
  "¿Qué te excita más?",
  "¿Tienes una posición favorita en la cama?",
  "¿Alguna vez tuviste un amor prohibido?",
  "¿Qué es lo más atrevido que has hecho en público?",
  "¿Te has sentido atraído por alguien de tu mismo sexo?",
  "¿Te gustaría probar juegos de rol?",
  "¿Alguna vez has enviado fotos atrevidas?",
  "¿Con quién fue tu mejor experiencia sexual?",
  "¿Has usado juguetes sexuales?",
  "¿Has tenido sexo en un lugar público?",
  "¿Cuál ha sido tu mayor decepción amorosa?",
  "¿Te gustaría que te dominen?",
  "¿Cuál ha sido tu peor vergüenza íntima?",
  "¿Te has enamorado a primera vista?",
  "¿Has soñado con alguien más estando en una relación?",
  "¿Cuánto tiempo podrías estar sin tener sexo?",
  "¿Qué parte del cuerpo te da más placer que no sea lo obvio?",
  "¿Has probado alguna vez algo tabú?",
  "¿Qué no te atreverías a hacer aunque te lo pidieran?",
  "¿Has usado tu imaginación para excitarte?",
  "¿Cuántas veces a la semana te gustaría tener sexo?",
  "¿Te gusta hablar sucio en la cama?",
  "¿Has probado el sexting?",
  "¿Te gustaría que te amarren?",
  "¿Cuál ha sido el lugar más incómodo donde has tenido sexo?",
  "¿Cuál es tu fantasía conmigo?",
  "¿Qué me harías si no hubiera límites?",
  "¿Has estado en una relación abierta?",
  "¿Qué no te gusta de mí y nunca me has dicho?",
  "¿Te gusta ver pornografía? ¿Qué tipo?",
  "¿Qué parte de tu cuerpo te parece más sexy?",
  "¿Has tenido sexo con alguien que apenas conocías?",
  "¿Te gustaría verme con poca ropa ahora?",
  "¿Qué harías si nos quedamos solos todo el fin de semana?",
   "¿Qué es algo que siempre has querido intentar conmigo y no te has atrevido?",
  "¿Te gustaría que experimentáramos con algo nuevo en la cama?",
  "¿Cuál es tu recuerdo más romántico conmigo?",
  "¿Alguna vez has sentido celos por alguien cercano a mí?",
  "¿Hay algo que te gustaría que hiciera más a menudo contigo?",
  "¿Qué te excita más: lo físico o lo emocional?",
  "¿Qué es lo más atrevido que has hecho por amor?",
  "¿Alguna vez has soñado algo íntimo conmigo y no me lo has dicho?",
  "¿Cuál ha sido tu mayor fantasía hasta ahora?",
  "¿Te gustaría que usáramos disfraces alguna vez?",
  "¿Has fingido alguna vez un orgasmo?",
  "¿Qué parte de tu cuerpo crees que me gusta más?",
  "¿Alguna vez revisaste mi celular en secreto?",
  "¿Alguna vez mentiste para evitar una pelea conmigo?",
  "¿Te gustaría que viviéramos juntos?",
  "¿Cuál fue tu primer pensamiento sobre mí cuando nos conocimos?",
  "¿Qué es algo que nunca te atreverías a contarle a nadie más que a mí?",
  "¿Qué te gustaría que hiciéramos más en pareja?",
  "¿Cuál ha sido el momento más embarazoso que has vivido conmigo?",
  "¿Cuál es tu recuerdo favorito de nosotros?",
  "¿Has tenido sueños eróticos conmigo últimamente?",
  "¿Qué te gustaría hacer en nuestra próxima cita?",
  "¿Cuál es tu miedo más grande en nuestra relación?",
  "¿Qué canción te recuerda a mí y por qué?",
  "¿Hay algo que todavía no sabes cómo decirme?",
  "¿Te consideras una persona celosa conmigo?",
  "¿Alguna vez tuviste dudas sobre nosotros?",
  "¿Cuál es tu guilty pleasure cuando piensas en mí?",
  "¿Qué opinas sobre las relaciones abiertas?",
  "¿Te gustaría tener hijos conmigo algún día?",
  "¿Qué es lo que más te atrae de mí físicamente?",
  "¿Sientes que somos compatibles sexualmente?",
  "¿Qué harías si supieras que alguien más me desea?",
  "¿Te molesta algo que no me has dicho?",
  "¿Qué cosa mía te vuelve loco/a?",
  "¿Qué fue lo primero que te enamoró de mí?",
  "¿Crees que soy dominante o sumiso/a?",
  "¿Te gustaría que planificáramos unas vacaciones juntos?",
  "¿Qué fantasía sexual te gustaría cumplir conmigo?",
  "¿Qué lugar público te gustaría intentar algo travieso conmigo?",
  "¿Qué tipo de mensajes calientes te gustan más?",
  "¿Te gustaría que te sorprendiera con lencería?",
  "¿Con qué frecuencia piensas en mí durante el día?",
  "¿Te ha gustado alguien más mientras estamos juntos?",
  "¿Qué parte de tu cuerpo te gustaría que explorara más?",
  "¿Qué es lo más atrevido que has hecho por alguien?",
  "¿Qué cosa nunca harías en la cama?",
  "¿Cuál ha sido tu beso favorito conmigo?",
  "¿Cuál es tu mayor debilidad cuando estamos juntos?",
  "¿Qué opinas sobre grabarnos (sin compartirlo)?",
   "¿Cuál ha sido tu mayor fantasía nunca contada?",
  "¿Con qué frecuencia piensas en el sexo?",
  "¿Qué parte de tu cuerpo te da más placer?",
  "¿Cuál ha sido tu lugar más raro donde lo hiciste?",
  "¿Tendrías una noche de pasión sin compromiso?",
  "¿Te gustaría grabarnos juntos?",
  "¿Has tenido sueños eróticos conmigo?",
  "¿Qué ropa interior prefieres usar y por qué?",
  "¿Has pensado en mí cuando te tocas?",
  "¿Qué parte de mi cuerpo te calienta más?",
  "¿Cuál es tu mayor inseguridad en la cama?",
  "¿Has sido infiel alguna vez?",
  "¿Qué cosa te da más morbo hacer en la intimidad?",
  "¿A qué edad fue tu primera vez?",
  "¿Tendrías sexo en público si nadie nos ve?",
  "¿Cuál es tu recuerdo más caliente?",
  "¿Has mentido para conseguir algo sexual?",
  "¿Alguna vez fingiste un orgasmo?",
  "¿Qué tipo de contenido ves en privado?",
  "¿Con qué frecuencia te masturbas?",
  "¿Has tenido sexo telefónico o por videollamada?",
  "¿Qué fantasía aún no has cumplido?",
  "¿Tendrías un trío?",
  "¿Con qué famoso/a te gustaría tener una noche loca?",
  "¿Qué harías si estuviéramos solos una noche sin límites?",
  "¿Te has enamorado de alguien prohibido?",
  "¿Has probado juguetes sexuales?",
  "¿Qué harías si te encontraras a tu ex desnudo/a?",
  "¿Cuál es tu peor experiencia íntima?",
  "¿Qué parte de mí te gustaría explorar más?",
  "¿Qué no harías jamás en la cama?",
  "¿Has usado alguna app para ligar?",
  "¿Tendrías una relación abierta?",
  "¿Te gustaría probar algo nuevo conmigo?",
  "¿Cuál es tu posición favorita y por qué?",
  "¿Has besado a alguien de tu mismo sexo?",
  "¿Cuál ha sido tu mayor locura por amor o deseo?",
  "¿Has tenido una relación secreta?",
  "¿Qué harías si te dijera que hoy todo se vale?",
  "¿Cuál es tu mayor miedo en una relación?",
  "¿Te han cachado alguna vez haciendo algo íntimo?",
  "¿Qué es lo que más te excita que haga?",
  "¿Qué parte mía has mirado más de lo que deberías?",
  "¿Qué no soportarías en la cama?",
  "¿Te ha gustado alguien mucho mayor o menor?",
  "¿Cuál fue tu peor cita?",
  "¿A quién extrañas más de tu pasado íntimo?",
  "¿Alguna vez te enamoraste de alguien por una noche?",
  "¿Has tenido sexo en un carro?",
  "¿Cuál fue tu mejor experiencia sexual y por qué?",
   "¿Has soñado alguna vez conmigo en plan sexy?",
  "¿Qué harías si estuviéramos solos en un hotel esta noche?",
  "¿Cuál es tu parte favorita de mi cuerpo y por qué?",
  "¿Te gusta cuando te miro de cierta forma? ¿Cuál?",
  "¿Qué te gustaría intentar conmigo pero no te has atrevido?",
  "¿Has fantaseado conmigo en una situación atrevida?",
  "¿Qué pensaste la primera vez que me viste?",
  "¿Qué ropa mía te gustaría quitarme con la boca?",
  "¿Cuál es el lugar más extraño donde te gustaría hacerlo?",
  "¿Qué te gustaría que hiciera yo sin que me lo pidieras?",
  "¿Me besarías enfrente de tus amigos? ¿Dónde?",
  "¿Has tenido pensamientos atrevidos hoy?",
  "¿Qué es lo más travieso que has hecho sin que yo lo sepa?",
  "¿Con qué frecuencia piensas en mí en la ducha?",
  "¿Te has imaginado una escena de película conmigo?",
  "¿Has sentido celos de alguien que me mire?",
  "¿Cómo sería tu cita perfecta conmigo (en detalle)?",
  "¿Qué parte de mí te provoca más cuando me ves?",
  "¿Has guardado una prenda mía por alguna razón especial?",
  "¿Cuál fue el momento exacto en que supiste que te atraía?",
  "¿Te gustaría que probáramos algo nuevo juntos? ¿Qué?",
  "¿Qué no harías con nadie más, pero sí conmigo?",
  "¿Qué parte del juego te gusta más, verdad o reto?",
  "¿Me has espiado alguna vez en silencio?",
  "¿Qué harías si yo te dijera ‘haz lo que quieras conmigo’?",
  "¿Me describirías con una palabra provocativa? ¿Por qué?",
  "¿Cuál fue tu primera impresión de mis besos?",
  "¿Cómo sería una noche perfecta entre nosotros?",
  "¿Qué te gustaría que usara solo para ti?",
  "¿Cuál es el recuerdo más caliente que tienes conmigo?",
  "¿Qué piensas cuando me ves distraído/a?",
  "¿Te gustaría tener un código secreto solo para cosas atrevidas?",
  "¿Qué canción describe mejor cómo te hago sentir?",
  "¿Qué tipo de mensajes te excita recibir de mí?",
  "¿Has soñado con que te tomaba por sorpresa?",
  "¿Qué te enloquece más: mis ojos, mi voz o mis besos?",
  "¿Qué secreto sensual te gustaría contarme algún día?",
  "¿Qué me harías si te doy carta blanca por una hora?",
  "¿Qué harías si te susurrara algo provocador en público?",
  "¿Hay alguna película que te haya recordado a nosotros?",
  "¿Qué tipo de beso es tu favorito y por qué?",
  "¿Te gustaría una noche sin reglas conmigo?",
  "¿Qué piensas cuando estamos cerca y no hay nadie?",
  "¿Has pensado en grabarnos alguna vez?",
  "¿Qué parte de tu cuerpo crees que más me gusta? ¿Acerté?",
  "¿Qué me harías si nadie pudiera vernos por 10 minutos?",
  "¿Has hecho algo travieso pensando en mí?",
  "¿Me contarías una fantasía tuya aunque fuera muy loca?",
  "¿Te animarías a hacer algo atrevido en un lugar público?",
  "¿Qué provocaría que perdieras el control conmigo?",
   "¿Alguna vez te has sentido inseguro/a de tu cuerpo?",
  "¿Qué es lo más inmaduro que haces todavía?",
  "¿Cuál fue la última vez que lloraste y por qué?",
  "¿Te has sentido celoso/a recientemente?",
  "¿Cuál es tu peor hábito en secreto?",
  "¿Qué es lo más raro que buscas en Google?",
  "¿Has dicho una mentira hoy?",
  "¿Tienes algún miedo infantil que aún no superas?",
  "¿Te da vergüenza algo que hiciste esta semana?",
  "¿Cuál es tu recuerdo más vergonzoso de la escuela?",
  "¿Has stalkeado recientemente a alguien en redes?",
  "¿Has ocultado algo importante a tu familia?",
  "¿Te has sentido atraído por alguien prohibido?",
  "¿Qué es lo más cruel que has dicho sin querer?",
  "¿Cuál es tu mayor inseguridad al estar en pareja?",
  "¿Has fingido estar bien solo para no preocupar?",
  "¿Hay algo que te avergüenza de tu pasado?",
  "¿Alguna vez tuviste un pensamiento que te dio miedo?",
  "¿Qué te incomoda más de ti mismo/a?",
  "¿Qué parte de tu cuerpo odias secretamente?",
  "¿Tienes envidia de alguien ahora mismo?",
  "¿Qué crees que piensan de ti cuando no estás?",
  "¿Te has sentido alguna vez como un fracaso?",
  "¿Tienes secretos que nadie conoce?",
  "¿A quién le tienes una envidia silenciosa?",
  "¿Te cuesta confiar en los demás?",
  "¿Has manipulado a alguien alguna vez?",
  "¿Hay alguien a quien no le has pedido perdón aún?",
  "¿Tienes una personalidad diferente en redes?",
  "¿Hay algo que jamás le dirías a tus padres?",
  "¿Has sentido que no eres suficiente para alguien?",
  "¿Guardas rencor hacia alguien todavía?",
  "¿Sientes que te conocen realmente?",
  "¿Has sido infiel en tus pensamientos?",
  "¿Te molesta no tener control sobre algo?",
  "¿Qué te hace sentir más inseguro al hablar?",
  "¿Alguna vez te burlaste de alguien sin que lo notara?",
  "¿Te han rechazado recientemente?",
  "¿Cuál fue tu mayor decepción este año?",
  "¿Quién te ha hecho llorar más en tu vida?",
  "¿Te gustaría cambiar algo de tu personalidad?",
  "¿Cuál es tu defecto más evidente?",
  "¿Has tenido celos de tu mejor amigo/a?",
  "¿Qué te impide confiar 100% en alguien?",
  "¿Qué te hace sentir inferior?",
  "¿Has hecho ghosting sin remordimiento?",
  "¿Qué tema siempre evitas en conversaciones?",
  "¿A qué le temes más: soledad o rechazo?",
  "¿Has traicionado a alguien?",
  "¿Qué harías si supieras que alguien habla mal de ti?",
  "¿Tienes una adicción que aún no admites?"
  // Continúa llenando hasta llegar a 200…
];


const retos = [
  "Bésame donde más te guste durante 30 segundos.",
  "Hazme un masaje sin usar las manos.",
  "Lámeme el cuello lentamente.",
  "Quítate una prenda con sensualidad.",
  "Haz un striptease improvisado.",
  "Susúrrame una fantasía tuya al oído.",
  "Mándame un mensaje caliente como si no estuviéramos aquí.",
  "Baila sexy para mí por un minuto.",
  "Hazme gemir sin tocarme directamente.",
  "Lámeme una parte del cuerpo que no esperaría.",
  "Descríbeme cómo sería tu noche perfecta conmigo.",
  "Hazme reír usando un tono sexy.",
  "Imita cómo me ves cuando estoy excitado.",
  "Dime cómo te gustaría que te tocara.",
  "Hazme una videollamada hot de mentira.",
  "Manda un mensaje picante a mi celular.",
  "Ponme una canción sexy y baila encima mío.",
  "Tócame sin usar las manos por 15 segundos.",
  "Haz sonidos como si estuviéramos en pleno acto.",
  "Dibújame con el dedo en alguna parte de tu cuerpo.",
  "Haz como si estuviéramos en un hotel.",
  "Muérdeme suavemente donde tú elijas.",
  "Mándame una foto atrevida después del juego.",
  "Bésame en una parte que no haya sido besada hoy.",
  "Tápame los ojos y sorpréndeme.",
  "Descríbeme una escena hot entre nosotros.",
  "Hazme una propuesta indecente.",
  "Haz una fantasía como si fuera un papel de rol.",
  "Haz un video sexy y muéstramelo.",
  "Haz un reto sin hablar, solo usando gestos.",
  "Bésame con los ojos cerrados durante 10 segundos.",
  "Hazme un cumplido mientras me acaricias.",
  "Haz como si me sedujeras por primera vez.",
  "Lée un texto erótico como si lo estuvieras viviendo.",
  "Ponte sobre mí y no digas nada por 20 segundos.",
  "Dime en qué parte del cuerpo quieres que te bese.",
  "Actúa como si estuvieras muy excitado.",
  "Hazme reír mientras me das un beso.",
  "Tócate frente a mí (de forma sexy y controlada).",
  "Hazme una pregunta íntima y responde tú primero.",
  "Déjame una marca donde nadie la vea.",
  "Dime qué me harías si estuviéramos solos en la playa.",
   "Bésame sin usar los labios durante 15 segundos.",
  "Hazme un striptease improvisado con la música que yo elija.",
  "Léeme un mensaje caliente en voz baja al oído.",
  "Haz un baile sensual para mí.",
  "Dame un masaje en la espalda sin usar las manos.",
  "Hazme reír en menos de 30 segundos o pierdes una prenda.",
  "Susúrrame 3 cosas que te gustaría hacerme.",
  "Haz contacto visual por 30 segundos sin reírte.",
  "Hazme una confesión al oído sin que te escuche nadie más.",
  "Lámeme el cuello lentamente por 10 segundos.",
  "Dime tu fantasía favorita como si fuera una historia real.",
  "Imita cómo te gustaría que te besara.",
  "Escríbeme algo provocador en la piel con tu dedo.",
  "Hazme una videollamada sexy con la cámara apagada.",
  "Hazme una pregunta incómoda, pero tú también debes responderla.",
  "Esconde algo en tu ropa y haz que lo encuentre con los ojos cerrados.",
  "Mándame un mensaje picante sin usar emojis.",
  "Describeme con detalle tu última fantasía conmigo.",
  "Bésame donde tú elijas, sin avisar.",
  "Haz un reto con los ojos vendados que yo elija.",
  "Hazme reír con un chiste muy subido de tono.",
  "Haz un dibujo en mi piel con tu lengua.",
  "Búscame un apodo sexy y llámame así el resto del juego.",
  "Haz que me sonroje con una frase directa.",
  "Déjame un beso marcado en una parte inesperada.",
  "Haz que adivine en qué parte quieres ser besado/a.",
  "Baila sin música como si estuviéramos en una fiesta íntima.",
  "Tócame sin usar las manos por 15 segundos.",
  "Haz que te sonría sin tocarme.",
  "Cuéntame una historia erótica como si fuera real.",
  "Pídeme un favor caliente sin usar palabras.",
  "Hazme una propuesta indecente en serio.",
  "Cántame algo sensual como si fueras un artista.",
  "Haz un reto al azar de otro juego sin decir cuál.",
  "Hazme un cumplido cada 5 minutos hasta que acabe el juego.",
  "Hazme un reto que implique usar la lengua.",
  "Hazme una videollamada fingiendo que estás solo/a.",
  "Descríbeme cómo sería una noche perfecta contigo.",
  "Haz como si me sedujeras en un bar por primera vez.",
  "Haz que te suplique por algo durante 10 segundos.",
  "Envía un audio diciendo algo subido de tono, como si fuera accidental.",
  "Imita cómo sería una escena romántica de película conmigo.",
  "Escríbeme una carta caliente en 3 oraciones.",
  "Actúa como si fuéramos completos desconocidos coqueteando.",
  "Bésame como si fuera la última vez.",
  "Dibuja algo travieso y muéstramelo sin explicarlo.",
  "Haz un reto al azar mientras mantienes contacto visual.",
  "Tócame donde más te gusta sin decirme nada.",
  "Susurra algo que quieras esta noche y no repitas.",
  "Esconde una nota caliente y haz que la encuentre.",
  "Haz un striptease lento durante 1 minuto.",
  "Imita a alguien teniendo un orgasmo.",
  "Haz un baile sexy sin música.",
  "Envía un emoji caliente a tu pareja sin contexto.",
  "Hazme reír usando solo gemidos.",
  "Tócame con los ojos vendados y adivina qué parte es.",
  "Súbete a la mesa y baila como si estuvieras en un club.",
  "Susúrrame algo sucio al oído.",
  "Hazme un cumplido íntimo muy específico.",
  "Bésame sin usar los labios.",
  "Haz una llamada fingiendo estar muy excitado/a.",
  "Dime qué fantasía tienes conmigo y actúala por 30 seg.",
  "Hazme un baile privado como si fueras stripper.",
  "Recréame tu primera vez en 1 minuto.",
  "Hazme reír sin usar palabras.",
  "Cambia una prenda con la mía.",
  "Haz como si tuvieras un fetiche muy raro.",
  "Ponte en cuatro y espera lo que venga.",
  "Haz de cuenta que estamos en un lugar público.",
  "Descríbeme detalladamente cómo me besarías.",
  "Actúa como si estuvieras celoso/a y exige atención.",
  "Muerde suavemente la parte del cuerpo que yo elija.",
  "Haz un gemido por cada letra de mi nombre.",
  "Mándame una nota de voz sexy (aunque estemos juntos).",
  "Tómame de la cintura y báilame muy pegado.",
  "Haz un roleplay corto donde eres mi fan obsesivo/a.",
  "Cántame una canción como si estuvieras enamorado/a.",
  "Haz un sonido sexy cada vez que yo hable por 1 minuto.",
  "Pide perdón como si hubieras roto mi corazón.",
  "Haz un video actuando como influencer sensual.",
  "Pide que te den un beso donde tú elijas.",
  "Tápate los ojos y deja que te sorprenda.",
  "Simula que me das un masaje... ¡con los pies!",
  "Repite todo lo que diga por 2 minutos.",
  "Simula una escena de película romántica.",
  "Haz que me sonroje sin tocarme.",
  "Tómame de la mano y guíame a una pose sexy.",
  "Haz una historia de Instagram actuada muy seductora.",
  "Mírame sin hablar durante 1 minuto y luego actúa.",
  "Pídele al otro que te diga algo que no se ha atrevido.",
  "Haz una escena de celos por mi ex imaginaria/o.",
  "Haz como si fueras un personaje famoso seductor.",
  "Actúa como si no supieras besar y pide una clase.",
  "Hazme una promesa íntima con total seriedad.",
  "Actúa como si estuvieras en una película para adultos.",
  "Finge que me estás conquistando por primera vez.",
  "Haz un TikTok sexy... aunque no lo publiques.",
  "Hazme una pregunta picante sin reírte.",
  "Haz un movimiento de cadera que te gustaría usar conmigo.",
  "Descríbeme una fantasía que involucre comida.",
   "Haz una imitación sexy de mí durante 30 segundos.",
  "Lame algo de mi cuerpo con los ojos vendados.",
  "Susurra algo muy provocador en mi oído.",
  "Hazme una videollamada sexy (sin ropa) aunque estemos juntos.",
  "Ponte mi ropa interior por 5 minutos.",
  "Haz un baile sexy con la canción que yo elija.",
  "Hazme una pregunta incómoda y respóndela tú también.",
  "Baila encima de mí sin música durante 1 minuto.",
  "Escríbeme algo erótico en alguna parte del cuerpo.",
  "Mándame una nota de voz diciéndome lo que me harías esta noche.",
  "Hazme reír con una historia sensual inventada.",
  "Actúa como si tuvieras un fetiche raro conmigo por 1 minuto.",
  "Haz una escena de celos muy exagerada.",
  "Bésame con los ojos cerrados y las manos atadas (imaginario).",
  "Recrea nuestra primera cita pero como si fueras una estrella de cine.",
  "Haz una escena de película romántica improvisada.",
  "Hazme un cumplido atrevido usando solo rimas.",
  "Pasa un cubo de hielo por mi cuello lentamente.",
  "Descríbeme cómo me verías en tu fantasía más atrevida.",
  "Dime 3 cosas que te excitan y demuéstrame una sin hablar.",
  "Dame un apodo sexy que usarás el resto del juego.",
  "Haz que me sonroje con una confesión íntima.",
  "Cántame una canción como si estuvieras seduciéndome.",
  "Léeme un texto erótico como si fuera una historia real.",
  "Haz un striptease con una sola prenda.",
  "Descríbeme lo que me harías con solo una palabra por frase.",
  "Hazme reír mientras haces algo provocador.",
  "Dibuja en mi espalda con tu dedo lo que más te gusta de mí.",
  "Bésame como si fuera la última vez que me verás.",
  "Pide algo indecente como si fueras un personaje de película.",
  "Actúa como si no me conocieras pero quisieras seducirme.",
  "Hazme una serenata con la voz más sensual que tengas.",
  "Sopla suavemente en mi cuello por 10 segundos.",
  "Pon una canción que te caliente y actúa según ella.",
  "Escríbeme una carta breve como si me desearas en secreto.",
  "Haz un reto que tú mismo inventes ahora y que me deje pensando.",
  "Pídeme algo atrevido por mensaje de texto ahora.",
  "Mírame a los ojos y dime algo que nunca me has dicho.",
  "Tócame la mano como si fueras a confesar algo íntimo.",
  "Hazme un retrato sexy con lápiz en 2 minutos.",
  "Imita a alguien intentando seducirme.",
  "Actúa como si estuviéramos en un hotel de película.",
  "Hazme cerrar los ojos y descríbeme lo que estás pensando hacerme.",
  "Hazme una propuesta atrevida que te gustaría intentar.",
  "Inventa un reto que incluya besos, tiempo y un lugar del cuerpo.",
  "Hazme una pregunta atrevida y prométeme cumplirla.",
  "Hazme una broma sensual sin decir una sola palabra directa.",
  "Esconde un mensaje sexy en alguna parte de la habitación.",
  "Hazme sudar sin tocarme (usa palabras).",
  "Dame una orden atrevida como si fueras mi jefe/a en secreto.",
   "Habla como un robot durante 3 minutos.",
  "Envía un emoji aleatorio a tu mamá sin contexto.",
  "Cambia tu nombre en WhatsApp por algo ridículo por 1 hora.",
  "Graba un audio cantando una canción ridícula.",
  "Dibuja un autorretrato con los ojos cerrados.",
  "Publica una historia diciendo 'me hackearon... o no'.",
  "Escribe con la mano contraria por 3 minutos.",
  "Haz 10 sentadillas diciendo 'yo soy fabuloso/a'.",
  "Envía un mensaje cariñoso a tu ex (solo si hay confianza).",
  "Habla con acento español por 5 minutos.",
  "Pon una selfie con cara rara como perfil 10 minutos.",
  "Haz de cuenta que eres influencer y graba una recomendación.",
  "Haz una llamada falsa y pide pizza en voz sexy.",
  "Haz una historia diciendo que amas los pepinos.",
  "Tómate una foto con una pose exageradamente sensual.",
  "Di tres cosas buenas de la persona que menos te cae.",
  "Haz como que lloras como actor de novela.",
  "Envía un meme vergonzoso a alguien al azar.",
  "Baila sin música durante 30 segundos.",
  "Léenos tu último mensaje recibido en voz alta.",
  "Actúa como un bebé por un minuto.",
  "Deja que alguien elija tu foto de perfil por 15 min.",
  "Cambia tu fondo de pantalla por algo vergonzoso.",
  "Llama a alguien y dile que soñaste con él/ella.",
  "Dibuja algo con los pies y muéstralo.",
  "Canta el coro de tu canción más cursi favorita.",
  "Haz un poema improvisado sobre tu comida favorita.",
  "Haz sonidos de animales por un minuto sin parar.",
  "Dinos tu peor apodo de la infancia.",
  "Haz una imitación de un famoso y adivinen quién.",
  "Di algo vergonzoso que te haya pasado este mes.",
  "Haz 5 poses para fotos de Instagram sin reírte.",
  "Describe tu crush usando solo objetos.",
  "Pide perdón al aire por cualquier cosa.",
  "Haz una historia actuando como influencer dramático.",
  "Canta una canción con la boca cerrada.",
  "Haz una declaración de amor a una silla.",
  "Haz como que estás dando un discurso presidencial.",
  "Lee un mensaje tuyo viejo en voz alta.",
  "Cuenta una historia inventada súper dramática.",
  "Inventa una palabra y úsalas en una oración seria.",
  "Envía una frase motivacional absurda a tu grupo.",
  "Baila como si estuvieras en una fiesta de los 80.",
  "Haz de cuenta que eres un chef de televisión.",
  "Haz como que estás vendiendo una pluma de oro.",
  "Camina en cámara lenta por la habitación.",
  "Escribe un texto solo usando emojis.",
  "Ponte algo al revés y no expliques por qué.",
  "Di tu frase de película inventada favorita.",
  "Haz una imitación de tu profe o jefe."
  // Continúa llenando hasta llegar a 200…
];

